"""tools/REPORT.md in the language repo: regenerated on every full build;
the section between the manual markers is preserved."""
import json
import re
from collections import Counter

from .freq import MIN_SHARE, N_SUB_SURFACES, N_WORDFREQ
from .util import STATS

MANUAL_BEGIN = "<!-- manual:begin -->"
MANUAL_END = "<!-- manual:end -->"


def kelly_crosscheck(env, words):
    if not env.spec.kelly_file:
        return None
    path = env.cache / env.spec.kelly_file
    if not path.exists():
        return None
    data = json.loads(path.read_text())
    tag = {}

    def walk(o):
        if isinstance(o, dict):
            w, lv = o.get("word") or o.get("lemma"), o.get("cefr") or o.get("level")
            if isinstance(w, str) and isinstance(lv, str) and lv in ("A1", "A2", "B1", "B2", "C1", "C2"):
                for part in re.split(r"[,/]\s*", w):
                    tag.setdefault(part.strip().lower(), lv)
            for v in o.values():
                walk(v)
        elif isinstance(o, list):
            for v in o:
                walk(v)
    walk(data)
    if not tag:
        return None
    levels = ["A1", "A2", "B1", "B2", "C1", "C2"]
    conf = Counter()
    for w in words:
        k = tag.get(w["lemma"])
        if k:
            conf[(w["lv"], k)] += 1
    n = sum(conf.values())
    pack_levels = [lv for lv in env.spec.level_ids if lv in levels]
    exact = sum(conf[(a, a)] for a in pack_levels)
    near = sum(v for (a, b), v in conf.items() if abs(levels.index(a) - levels.index(b)) <= 1)
    return {"matched": n, "tagged": len(tag), "exact": exact, "within1": near,
            "table": {a: [conf[(a, b)] for b in levels] for a in pack_levels}}


def write_report(env, ctx):
    sp = env.spec
    words = ctx["words"]
    S = STATS
    path = env.repo / sp.report_file
    manual = ""
    if path.exists():
        old = path.read_text()
        if MANUAL_BEGIN in old and MANUAL_END in old:
            manual = old[old.index(MANUAL_BEGIN): old.index(MANUAL_END) + len(MANUAL_END)]
    if not manual:
        manual = f"{MANUAL_BEGIN}\n{MANUAL_END}"
    L = []
    a = L.append
    a(f"# Build report - {sp.report_title}\n")
    a("Generated by `tools/build_pack.py` on every full run. Everything outside the "
      "`manual` markers is regenerated; the manual section (QA verdicts, check output) is preserved.\n")
    tm = S.get("tag_meta", {})
    a("## Tagging\n")
    a(f"- Tagger: {S.get('tagger')} (parser and NER disabled).")
    a(f"- Corpus: {S['corpus']['n_ita']:,} Tatoeba {sp.name_en} sentences; {S['corpus']['n_with_en']:,} have an "
      f"English translation and were tagged ({tm.get('tokens', 0):,} tokens).")
    a(f"- Tagging wall time: **{tm.get('seconds')}s** ({sp.spacy_n_process} processes; cached in `.cache/derived/tagged_*.jsonl.gz`, "
      f"keyed by tag version + spaCy/model version + corpus signature).")
    a(f"- Sentence-initial capitals lowercased before tagging (truecasing, proper nouns kept): "
      f"{tm.get('truecased_initials', 0):,} sentences.")
    a(f"- Sentences with a permissively licensed recording: {S['corpus']['n_audio']:,}.\n")
    fr = S["freq"]
    a("## Lemma + POS resolution\n")
    a("Each subtitle / wordfreq surface form is split over the (lemma, POS) pairs it takes in the tagged "
      f"corpus (pairs under {int(MIN_SHARE*100)}% share dropped). Surfaces unseen in the corpus fall back "
      "to simplemma.\n")
    a("| list | surfaces resolved from corpus | simplemma fallback |")
    a("|---|---|---|")
    a(f"| {sp.spoken_freq_label or f'subtitles (top {N_SUB_SURFACES:,} surfaces)'} | {fr['sub_surfaces'].get('corpus', 0):,} | "
      f"{fr['sub_surfaces'].get('fallback', 0):,} |")
    a(f"| wordfreq top {N_WORDFREQ:,} | {fr['wf_surfaces'].get('corpus', 0):,} | {fr['wf_surfaces'].get('fallback', 0):,} |")
    rs = S.get("resolution", {})
    a(f"\nFallback lemmas whose POS could not be attached from another surface: {fr['unknown_pos_keys']:,}. "
      f"Clitic compounds resolved to the verb by suffix stripping: {rs.get('clitic_compounds_resolved', 0):,} "
      f"distinct forms. Tokens with no dictionary-validated lemma (kept, never selected as words): "
      f"{sum(rs.get('unresolved_tokens_by_pos', {}).values()):,}.\n")
    a("## Word-selection funnel\n")
    a(f"Candidate pool: {S['pool_keys']:,} (lemma, POS) keys in blended-rank order, one POS per lemma "
      f"(its best-ranked corpus POS{sp.article_pool_note}), plus forced items.\n")
    a("| Exclusion | Count | Examples |")
    a("|---|---|---|")
    for r, c in sorted(S["excluded"].items(), key=lambda kv: -kv[1]):
        a(f"| {r} | {c:,} | {', '.join(S['excluded_examples'].get(r, [])[:12])} |")
    fo = S["forced"]
    a(f"\nForced {sp.level_ids[0]} items ({sp.forced_description}): {fo['included']}/{fo['requested']} included"
      + (f"; missing: {', '.join(fo['missing'])}" if fo["missing"] else "") + ".")
    a(f"Word ids reused from v1 for unchanged (lemma, pos): {S['ids_reused_from_v1']:,}; the rest are new "
      "ids above w2000 (v1 ids of words whose POS/lemma was wrong are retired, not reassigned).\n")
    lv = Counter(w["lv"] for w in words)
    pos = Counter(w["pos"] for w in words)
    a(f"Levels: {dict(sorted(lv.items()))}. POS: {dict(pos.most_common())}.\n")
    st = S["sentences"]
    a("## Sentences\n")
    a(f"- Final sentences: **{st['final_sentences']:,}**, {st['with_audio']:,} with audio "
      "(`https://tatoeba.org/audio/download/<audio_id>`).")
    a(f"- Word coverage: 0 = {st['coverage_0']}, 1 = {st['coverage_1']}, 2 = {st['coverage_2']}.")
    if st["zero_sentence_words"]:
        a(f"- Words with no sentence: {', '.join(st['zero_sentence_words'])}.")
    a(f"- Candidate sentences (terminal punctuation, 3-{sp.max_len} tokens, content lemmas in pack/top-3000, "
      f">=1 link): {st['candidates']:,}. Rejected for a content lemma outside pack/top-3000: "
      f"{st.get('content_lemma_outside_pack_top3000', 0):,}.")
    if sp.marked_past_name:
        lower = "/".join(sp.level_ids[:-1])
        a(f"- {sp.marked_past_name}: {st.get('candidates_with_passato_remoto', 0):,} candidates contain one; "
          f"{st['remoto_candidates_blocked_for_A1_A2']:,} were blocked for {lower} words; "
          f"{st['remoto_in_final']} in the final set (all lv {sp.level_ids[-1]}).")
    a(f"- Primary word level of each sentence: {st['primary_by_level']}.")
    a("- Token-length distribution of the final set:\n")
    a("| tokens | " + " | ".join(st["length_hist"]) + " |")
    a("|---|" + "---|" * len(st["length_hist"]))
    a("| sentences | " + " | ".join(str(v) for v in st["length_hist"].values()) + " |\n")
    kc = kelly_crosscheck(env, words)
    if kc:
        a("## Kelly CEFR cross-check (sanity only, not shipped)\n")
        a(f"{kc['matched']:,} of {sp.n_words:,} lemmas matched Kelly. Exact level agreement {kc['exact']}/{kc['matched']} "
          f"= {100*kc['exact']/max(kc['matched'],1):.1f}%; within one level {kc['within1']}/{kc['matched']} "
          f"= {100*kc['within1']/max(kc['matched'],1):.1f}%.\n")
        a("| pack \\ kelly | A1 | A2 | B1 | B2 | C1 | C2 |")
        a("|---|---|---|---|---|---|---|")
        for k, row in kc["table"].items():
            a(f"| **{k}** | " + " | ".join(str(x) for x in row) + " |")
        a("")
    a("## Top 100 by rank (lemma [pos] gloss)\n")
    a("```")
    for w in sorted(words, key=lambda x: x["rank"])[:100]:
        a(f"{w['rank']:>4} {w['w']} [{w['pos']}] {w['en']}")
    a("```\n")
    a(manual)
    path.write_text("\n".join(L) + "\n")
