#!/usr/bin/env python3
"""Generate packs/X/*.js from packs/X/*.json.

The engine loads pack data as plain JS constants (so dev mode works from file://
and build.sh can inline them with awk, no JSON loader needed):

    pack.json      -> pack.js       const PACK=...;
    words.json     -> words.js      const WORDS=...;
    sentences.json -> sentences.js  const SENTENCES=...;
    lessons.json   -> lessons.js    const LESSONS=...;   (optional file)

Usage: python3 tools/jsonify_pack.py packs/zh [--check]
  --check  write nothing; exit 1 if any .js is missing or differs from what
           would be generated (used by validate_pack.py).
"""
import json
import os
import sys

FILES = [("pack", "PACK", True), ("words", "WORDS", True),
         ("sentences", "SENTENCES", True), ("lessons", "LESSONS", False)]


def render(const, data):
    # "</" -> "<\\/" keeps a "</script>" inside pack text from closing the inline
    # <script> build.sh wraps this file in; "<\\/" is the same string in JS.
    body = json.dumps(data, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    return f"// generated by tools/jsonify_pack.py from the .json beside this file; do not edit\nconst {const}={body};\n"


def expected_outputs(packdir):
    out = {}
    for stem, const, required in FILES:
        src = os.path.join(packdir, stem + ".json")
        if not os.path.exists(src):
            if required:
                raise SystemExit(f"jsonify_pack: missing required {src}")
            continue
        with open(src, encoding="utf-8") as f:
            data = json.load(f)
        out[os.path.join(packdir, stem + ".js")] = render(const, data)
    return out


def main(argv):
    args = [a for a in argv if not a.startswith("--")]
    check = "--check" in argv
    if len(args) != 1:
        print(__doc__, file=sys.stderr)
        return 2
    packdir = args[0].rstrip("/")
    outs = expected_outputs(packdir)
    stale = []
    for path, text in outs.items():
        cur = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                cur = f.read()
        if cur == text:
            continue
        if check:
            stale.append(path)
        else:
            with open(path, "w", encoding="utf-8") as f:
                f.write(text)
            print(f"wrote {path}")
    if check and stale:
        for p in stale:
            print(f"stale or missing generated file: {p} (run tools/jsonify_pack.py {packdir})")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
